In [2]:
import numpy as np
gradient = np.linspace(0, 1, 10)
print(gradient)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [3]:
import numpy as geek 
  
array = geek.arange(10).reshape(5, 2) 
print("Original array : \n", array) 
  
  
b = geek.zeros_like(array, float) 
print("\nMatrix b : \n", b) 
  
array = geek.arange(8)
print(array)
c = geek.zeros_like(array) 
print("\nMatrix c : \n", c)

Original array : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Matrix b : 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[0 1 2 3 4 5 6 7]

Matrix c : 
 [0 0 0 0 0 0 0 0]


In [5]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.sum(a, axis = 1)

array([ 6, 15])